### ISSUE TITLE
Create Notifications Page to Showcase System notifications

### ISSUE THREAD

**Issue by DennisRono** [DennisRono/shop-yangu#17]
- [ ] list new notifications
- [ ] add filter for finding notificatins easily
- [ ] add a loading skeleton when fetching notifications

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added functionality to list new notifications, implemented a filter for easily finding notifications, and added a loading skeleton when fetching notifications. Updated the Notifications component to use the API for fetching notifications and implemented the required features.

You can review changes in this commit: https://github.com/mnmnk43434/DennisRono-shop-yangu-17/commit/652542e7b042736554eb800adefa566415e47eae.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
